import { z } from "zod";

export const patientPathologicalDataPayloadValidator = z.object({
    hospitalization: z.boolean().optional(),
    hospitalizationDetails: z.string().trim().optional(),
    diabetes: z.boolean().optional(),
    diabetesDetails: z.string().trim().optional(),
    thyroidDiseases: z.boolean().optional(),
    thyroidDiseasesDetails: z.string().trim().optional(),
    hypertension: z.boolean().optional(),
    hypertensionDetails: z.string().trim().optional(),
    heartDiseases: z.boolean().optional(),
    heartDiseasesDetails: z.string().trim().optional(),
    trauma: z.boolean().optional(),
    traumaDetails: z.string().trim().optional(),
    cancer: z.boolean().optional(),
    cancerDetails: z.string().trim().optional(),
    tuberculosis: z.boolean().optional(),
    tuberculosisDetails: z.string().trim().optional(),
    transfusions: z.boolean().optional(),
    transfusionsDetails: z.string().trim().optional(),
    respiratoryDiseases: z.boolean().optional(),
    respiratoryDiseasesDetails: z.string().trim().optional(),
    gastrointestinalDiseases: z.boolean().optional(),
    gastrointestinalDiseasesDetails: z.string().trim().optional(),
    sexuallyTransmittedDiseases: z.boolean().optional(),
    sexuallyTransmittedDiseasesDetails: z.string().trim().optional(),
    chronicKidneyDisease: z.boolean().optional(),
    chronicKidneyDiseaseDetails: z.string().trim().optional(),
    other: z.boolean().optional(),
    otherDetails: z.string().trim().optional(),
});
