export enum SPECIALITIES {
    CARDIOLOGY = "Cardiology",
    PEDIATRICS = "Pediatrics",
    DERMATOLOGY = "Dermatology",
    GYNECOLOGY = "Gynecology",
    NEUROLOGY = "Neurology",
    ONCOLOGY = "Oncology",
    TRAUMATOLOGY = "Traumatology",
    OPHTHALMOLOGY = "Ophthalmology",
    PSYCHIATRY = "Psychiatry",
    ENDOCRINOLOGY = "Endocrinology",
    INFECTOLOGY = "Infectology",
    INTERNAL_MEDICINE = "Internal Medicine",
    RHEUMATOLOGY = "Rheumatology",
    UROLOGY = "Urology",
    OTOLARYNGOLOGY = "Otolaryngology",
    GASTROENTEROLOGY = "Gastroenterology",
    GENERAL_SURGERY = "General Surgery",
    PULMONOLOGY = "Pulmonology",
    NUTRITION = "Nutrition",
    FAMILY_MEDICINE = "Family Medicine",
    OTHERS = "Others",
}
