openapi: 3.0.0
info:
    title: MedLink API
    description: API documentation for MedLink application
    version: 1.0.0
paths:
    /allergie:
        put:
            summary: Add or update patient allergies data
            tags:
                - Allergies
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                foodAllergy:
                                    type: boolean
                                    description: Indicates if the patient has food allergies
                                foodAllergyDetails:
                                    type: string
                                    description: Details about the patient's food allergies
                                insectAllergy:
                                    type: boolean
                                    description: Indicates if the patient has insect allergies
                                insectAllergyDetails:
                                    type: string
                                    description: Details about the patient's insect allergies
                                medicineAllergy:
                                    type: boolean
                                    description: Indicates if the patient has medicine allergies
                                medicineAllergyDetails:
                                    type: string
                                    description: Details about the patient's medicine allergies
                                otherAllergies:
                                    type: boolean
                                    description: Indicates if the patient has other allergies
                                otherAllergiesDetails:
                                    type: string
                                    description: Details about the patient's other allergies
            responses:
                200:
                    description: Successfully added or updated patient allergies data
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    success:
                                        type: boolean
                                    payload:
                                        $ref: "#/components/schemas/PatientData"
                400:
                    description: Bad request
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    success:
                                        type: boolean
                                        example: false
                                    error:
                                        type: object
                                        properties:
                                            message:
                                                type: string
                                                example: Invalid input
                                            details:
                                                type: string
                                                example: Email is required
                401:
                    description: Unauthorized
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    success:
                                        type: boolean
                                        example: false
                                    error:
                                        type: object
                                        properties:
                                            message:
                                                type: string
                                                example: Unauthorized
                                            details:
                                                type: string
                                                example: INVALID_CREDENTIALS
                500:
                    description: Internal server error
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    success:
                                        type: boolean
                                        example: false
                                    error:
                                        type: object
                                        properties:
                                            message:
                                                type: string
                                                example: Server error
                                            details:
                                                type: string
                                                example: SERVER_ERROR
components:
    schemas:
        PatientData:
            type: object
            properties:
                id:
                    type: string
                    example: "672cd5cace845109a51a1c2e"
                email:
                    type: string
                    example: "Arjun.Russel@gmail.com"
                role:
                    type: string
                    example: "Patient"
                firstName:
                    type: string
                    example: "Ramiro"
                lastName:
                    type: string
                    example: "Blanda"
                dateOfBirth:
                    type: string
                    format: date-time
                    example: "2024-03-06T21:47:57.000Z"
                avatar:
                    type: string
                    example: "/uploads/avatars/1731027229425-IMG_2197.jpg"
                files:
                    type: array
                    items:
                        type: string
                clinicalData:
                    type: object
                    properties:
                        height:
                            type: number
                            example: 40
                        weight:
                            type: number
                            example: 925
                        bloodType:
                            type: string
                            example: "0+"
                        bloodPressureTrend:
                            type: string
                            example: "RISING"
                        isDonor:
                            type: boolean
                            example: true
                        hasAllergies:
                            type: boolean
                            example: false
                        hasChronicDiseases:
                            type: boolean
                            example: false
                        hasHealthyLifestyle:
                            type: boolean
                            example: true
                allergiesData:
                    type: object
                    properties:
                        foodAllergy:
                            type: boolean
                            example: true
                        foodAllergyDetails:
                            type: string
                            example: "Et dignissimos est. Ipsa sit qui molestiae ut accusantium unde est. Vel doloribus porro porro qui ipsa molestiae porro. Assumenda rerum dolores quibusdam aut et."
                        insectAllergy:
                            type: boolean
                            example: false
                        insectAllergyDetails:
                            type: string
                            example: "Exercitationem aut enim voluptas fuga asperiores voluptas vitae perferendis nihil. Voluptas alias voluptatem quam quos soluta sed veritatis reiciendis aperiam. Nostrum sequi a molestiae. Rerum iure aut pariatur quo et et consequatur. Eveniet mollitia voluptatibus aut. Sunt libero qui est deserunt omnis."
                        medicineAllergy:
                            type: boolean
                            example: false
                        medicineAllergyDetails:
                            type: string
                            example: "Minus in hic aliquid. Repellat sapiente non. Eos omnis accusamus et rerum quia id. Voluptatum consequatur exercitationem esse debitis."
                        otherAllergies:
                            type: boolean
                            example: false
                        otherAllergiesDetails:
                            type: string
                            example: "Non cupiditate laborum vel ab molestias est. Delectus sed omnis rerum sapiente non dolore rem rerum fuga. Quis pariatur quo aut. Minus veritatis id ullam numquam ut sint mollitia."
                documents:
                    type: array
                    items:
                        type: string
                medications:
                    type: array
                    items:
                        type: string
                authorizedDoctors:
                    type: array
                    items:
                        type: string
                status:
                    type: boolean
                    example: true
                createdAt:
                    type: string
                    format: date-time
                    example: "2024-11-07T14:59:22.105Z"
                updatedAt:
                    type: string
                    format: date-time
                    example: "2024-11-12T01:52:26.332Z"
